### ISSUE TITLE
Modify log-levels when creating global explanations

### ISSUE THREAD

**Issue by TobiasGoerke** [viadee/javaAnchorExplainer#12]
Only a few info-level log messages get created when constructing a single anchor.
Global explainers that aggregate local explanations accordingly spawn thousands of these log messages. While such log messages are relevant for the first scenario (that is why level info is set) they are impratical in the second one.
Unfortunately, SLF4J does not allow to change the log level at runtime. 

=> Find some way to change the log level to prevent bloated log files.

**Comment by fkoehne** [comment]
Why not shift this into debug level outputs?

**Comment by fkoehne** [comment]
On the server we can than switch spring profiles.

**Comment by TobiasGoerke** [comment]
The log output is most likely relevant when creating local explanations. Setting them to debug would mute any output in this scenario.

**Comment by fkoehne** [comment]
In my view, any relevant information (from a user perspective) should be contained in the calculation result. The info level is regularly understood as "interesting from an administrator perspective", i.e. "is the server started?" or "which modules are loaded?". Ok for you?

**Comment by TobiasGoerke** [comment]
This is okay for me. I've already reduced the amount of "irrelevant" info level log messages. So, global explanations are to include a number of messages, which is reasonable.
