### ISSUE TITLE
Move maven coordinates

### ISSUE THREAD

**Issue by fkoehne** [viadee/javaAnchorExplainer#5]
We should move the project (and the subprojects and dependent projects) to some kind of sub-folder (de.viadee.xai or de.viadee.anchor, ...). 
Background: Our maven central repo looks rather cluttered now.

**Comment by fkoehne** [comment]
Let's do both: de.viadee.xai.anchors

**Comment by AlexKroeker** [comment]
moved this project as well as the adapters to xai.anchor(.adapter)
