### ISSUE TITLE
ParallelSamplingService threading issue

### ISSUE THREAD

**Issue by AlexKroeker** [viadee/javaAnchorExplainer#7]
ParallelSamplingService is creating thousands of threads without destroying or reusing them.

**Comment by fkoehne** [comment]
Well, the executor does not get shut down for now. How did you measure the thread count? In theory the executor should manage (and limit) them.

**Comment by AlexKroeker** [comment]
Created the branch 'fix-threading-for-global-expl' where threading in sampling service is activated as well as created a test to ensure that these threads are destroyed - or at least it used less than 200 threads

**Comment by fkoehne** [comment]
Thanks, looks good for me. We could probably tune this some more by putting the Executor in a reusable singleton. This would however prohibit a per-call configuration of the degree of parallelization.
